[project]
name = "homeassistant-wattbox-300"
version = "0.1.0"
readme = "README.md"
license = "MIT"
license-files = [ "LICENSE" ]
authors = [ { name = "Joshua Peek" } ]
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]

[dependency-groups]
dev = [
    "homeassistant>=2025.4",
    "mypy>=1.12,<2",
    "pytest>=8,<10",
    "pytest-asyncio>=0.24,<2",
    "ruff>=0.2,<2",
]

[tool.ruff]
lint.extend-select = [ "I", "UP" ]

[tool.pyproject-fmt]
indent = 4

[tool.mypy]
explicit_package_bases = true
strict = true

[tool.pytest]
ini_options.testpaths = [ "tests" ]
ini_options.pythonpath = [ "." ]
ini_options.asyncio_default_fixture_loop_scope = "function"
ini_options.asyncio_mode = "auto"
